from django.db import models
import smtplib
from email.mime.text import MIMEText
from googlevoice import Voice

USERNAME_MAX_LENGTH = 25
PERSON_NAME_MAX_LENGTH = 25
PHONE_NUMBER_MAX_LENGTH = 20

GEDDIT_GMAIL = 'awib5dche9di@gmail.com'
GEDDIT_PASSWORD = '' # You should fill this in

class User(models.Model):
    # The id field is automatically generated by Django
    # id = models.IntegerField(primary_key=True)
    username = models.CharField(max_length=USERNAME_MAX_LENGTH, unique=True)
    first_name = models.CharField(max_length=PERSON_NAME_MAX_LENGTH)
    last_name = models.CharField(max_length=PERSON_NAME_MAX_LENGTH)
    email = models.EmailField()
    cell_phone = models.CharField(max_length=PHONE_NUMBER_MAX_LENGTH)

    @staticmethod
    def create_user(username, first_name, last_name, email, cell_phone):
        u = User(username=username, first_name=first_name, \
                last_name=last_name, email=email, cell_phone=cell_phone)
        u.save()

    @staticmethod
    def get_user(username):
        return User.objects.get(username=username)

    @staticmethod
    def delete_user(user):
        user.delete()

    def __unicode__(self):
        return self.last_name + ', ' + self.first_name

    def send_email(self, message, subject):
        msg = MIMEText(message)
        msg['Subject'] = subject
        msg['From'] = GEDDIT_GMAIL
        msg['To'] = self.email

        s = smtplib.SMTP('localhost')
        s.sendmail(GEDDIT_GMAIL, [self.email], msg.as_string())
        s.quit()

    def send_sms(self, message):
        voice = Voice()
        voice.login(GEDDIT_GMAIL, GEDDIT_PASSWORD)
        voice.send_sms(self.cell_phone, message)

CATEGORY_NAME_MAX_LENGTH = 100

class Category(models.Model):
    # Django will automatically generate this:
    # id = models.IntegerField()
    name = models.CharField(max_length=CATEGORY_NAME_MAX_LENGTH)

ITEM_NAME_MAX_LENGTH = 100
DESCRIPTION_NAME_MAX_LENGTH = 1000

class Item(models.Model):
    # Django will automatically generate this:
    # id = models.IntegerField()
    seller_user = models.ForeignKey(User)
    name = models.CharField(max_length=ITEM_NAME_MAX_LENGTH)
    description = models.CharField(max_length=DESCRIPTION_NAME_MAX_LENGTH)
    active = models.BooleanField()
    category = models.ForeignKey(Category)

class Filter(models.Model):
    # Django will automatically generate this:
    # id = models.IntegerField()
    user = models.ForeignKey(User)
    conditions = models.CharField(max_length=DESCRIPTION_NAME_MAX_LENGTH)
    timestamp = models.TimeField()

class Claim(models.Model):
    # Django will automatically generate this:
    # id = models.IntegerField()
    buyer = models.ForeignKey(User, related_name='buyer')
    seller = models.ForeignKey(User, related_name='seller')
    item = models.ForeignKey(Item)


