from django.db import models
import smtplib
from email.mime.text import MIMEText

USERNAME_MAX_LENGTH = 25
PERSON_NAME_MAX_LENGTH = 25

FROM_EMAIL = 'kxing@mit.edu'

class User(models.Model):
    # The id field is automatically generated by Django
    # id = models.IntegerField(primary_key=True)
    username = models.CharField(max_length=USERNAME_MAX_LENGTH, unique=True)
    first_name = models.CharField(max_length=PERSON_NAME_MAX_LENGTH)
    last_name = models.CharField(max_length=PERSON_NAME_MAX_LENGTH)
    email = models.EmailField()

    @staticmethod
    def create_user(username, first_name, last_name, email):
        u = User(username=username, first_name=first_name, \
                last_name=last_name, email=email)
        u.save()

    @staticmethod
    def get_user(username):
        return User.objects.get(username=username)

    @staticmethod
    def delete_user(user):
        user.delete()

    def __unicode__(self):
        return self.last_name + ', ' + self.first_name

    def send_email(self, message, subject):
        msg = MIMEText(message)
        msg['Subject'] = subject
        msg['From'] = FROM_EMAIL
        msg['To'] = self.email

        s = smtplib.SMTP('localhost')
        s.sendmail(FROM_EMAIL, [self.email], msg.as_string())
        s.quit()

ITEM_NAME_MAX_LENGTH = 100
DESCRIPTION_NAME_MAX_LENGTH = 1000

class Item(models.Model):
    item_id = models.IntegerField()
    seller_user_id = models.IntegerField()
    name = models.CharField(max_length=ITEM_NAME_MAX_LENGTH)
    description = models.CharField(max_length=ITEM_NAME_MAX_LENGTH)
    active = models.BooleanField()
    category = models.IntegerField()
